version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: videoai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: videoai
    ports:
      - "3306:3306"
    volumes:
      - ./sql/videoai.sql:/docker-entrypoint-initdb.d/videoai.sql

  redis:
    image: redis:7.2
    container_name: videoai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: videoai-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  rocketmq-namesrv:
    image: apache/rocketmq:5.3.1
    container_name: videoai-rmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"

  rocketmq-broker:
    image: apache/rocketmq:5.3.1
    container_name: videoai-rmq-broker
    depends_on:
      - rocketmq-namesrv
    environment:
      NAMESRV_ADDR: rocketmq-namesrv:9876
    command: sh mqbroker -n rocketmq-namesrv:9876 --enable-proxy
    ports:
      - "10911:10911"
      - "10909:10909"

